apiVersion: v1
kind: ConfigMap
metadata:
  name: service-c-cm
  namespace: dev
data:
  SERVER_PORT: '8080'
  SPRING_PROFILES_ACTIVE: dev
  TZ: 'Europe/Madrid'
  TRACES_ENDPOINT: 'http://jaeger-collector.istio-system.svc.cluster.local:9411'
  SERVICE_NODEJS_1: 'http://service-nodejs-1-svc/service-nodejs-1/time'
  